<?php
$title = 'Créer un menu';
$this->headTitle($title);
?>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />



<nav class="nav-breadcrumb">
    <div class="nav-wrapper">
        <div class="col s12">
            <?php echo $this->escapeHtml($title); ?>
        </div>
    </div>
</nav>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('cms/default', array('controller' => 'menu', 'action' => 'add'), true));

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();


?>

<div class="cf nestable-lists">
    <ul id="items1" class="items">
        <li class="list">Item 1-1</li>
    </ul>
    <ul id="items2" class="items">
        <?php foreach($categories as $categorie): ?>
            <li class="list g"><?= $categorie->getCtgrName() ?></li>
        <?php endforeach ?>
    </ul>
</div>

<div>

<div>



<script src="<?php echo $this->basePath('js/jquery.nestable.js') ?>"></script>
<script type="text/javascript" src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script type="text/javascript" src="http://www.pureexample.com/js/lib/jquery.ui.touch-punch.min.js"></script>

<script>
    $(document).ready(function()
    {
        $('#nestable').nestable()

        var nestablecount = 3;
        $('#appendnestable').click(function () {
            $('ol.dd-list').append('<li class="dd-item dd3-item" data-id="' + nestablecount + '">' +
                '<div class="dd-handle dd3-handle">Drag</div>' +
                '<div class="dd3-content" name="' + nestablecount + '">' +
                '<input type="text" value="" placeholder="item ' + nestablecount + '" style="height: 1rem" /></div></li>');
            nestablecount++;
        });

        var updateOutput = function(e)
        {
            var list   = e.length ? e : $(e.target),
                output = list.data('output');
            if (window.JSON) {
                output.val(window.JSON.stringify(list.nestable('serialize')));//, null, 2));
            } else {
                output.val('JSON browser support required for this demo.');
            }
        };

        $('#nestable-menu').on('click', function(e)
        {
            var target = $(e.target),
                action = target.data('action');
            if (action === 'expand-all') {
                $('.dd').nestable('expandAll');
            }
            if (action === 'collapse-all') {
                $('.dd').nestable('collapseAll');
            }
        });
        $('#nestable3').nestable();


        $("#items1,#items2,#items3").sortable({
            connectWith: "#items1,#items2,#items3",
            start: function (event, ui) {
                ui.item.toggleClass("highlight");
            },
            stop: function (event, ui) {
                ui.item.toggleClass("highlight");
            }
        });
        $("#items1,#items2,#items3").disableSelection();
    });
</script>

