<?php
$title = 'Liste des Menus';
$this->headTitle($title);
?>

<nav class="nav-breadcrumb">
    <div class="nav-wrapper">
        <div class="col s12">
            <?php echo $this->escapeHtml($title); ?>
        </div>
    </div>
</nav>

<a class="waves-effect waves-light btn" href="<?php echo $this->url('cms/default', array('controller' => 'menu', 'action'=>'add'));?>">Ajouter un menu</a>

<table class="striped">
    <tr>
        <th>Nom</th>
        <th></th>
    </tr>
    <?php foreach($menus as $menu):?>
        <tr>
            <td><?=$this->escapeHtml($menu->getMenuName())?>
            </td>
            <td>
                <a href="<?php echo $this->url('cms/default', array('controller' => 'menu', 'action' => 'delete','id' => $menu->getMenuId() )) ?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach?>
</table>