<div class="row">
    <div class=" s12 m7">
        <div class="card">
            <div class="card-image">
                <img style="max-height: 300px" src="<?php echo $this->basePath('/article/'.$article->getArtcImageFilename()) ?>">
                <span class="card-title"><h1><?php echo $article->getArtcTitle(); ?></h1>e</span>
            </div>
            <div class="card-content" style="min-height: 200px;">
                <p><?php echo $article->getArtcIntroText(); ?></p>
                <p><?php echo $article->getArtcFullText(); ?></p>
            </div>
            <div class="card-action">
                <?php echo $this->escapeHtml($article->getArtcCreated()->format('Y-m-d H:i:s'));?>
                <blockquote> by <?php if (is_object($article->getAuthor())) echo $this->escapeHtml($article->getAuthor()->getUsrName());?> </blockquote>
            </div>
        </div>
    </div>

    <div>
        <?php foreach($article->getComments() as $comment): ?>
            <div class="card blue-grey lighten-2" style="padding: 10px">
                <p><?php echo $this->escapeHtml($comment->getComTitle());?></p>
                <p><?php echo $this->escapeHtml($comment->getComText());?></p>
                <p><?php echo $this->escapeHtml($comment->getComUsername());?></p>
                <p><?php if (is_object($comment->getComCreated())) echo $this->escapeHtml($comment->getComCreated()->format('Y-m-d H:i:s'));?></p><!-- Notice: getArtcCreated() returns an object convert to string -->
            </div>
        <?php endforeach ?>
    </div>

    <div>
        <?php $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->url('cms/default', array('controller' => 'comment', 'action' => 'add'), true)); //'contact/process'));
            $form->setAttribute('method', 'post');

            echo $this->form()->openTag($form);
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        ?>
    </div>
</div>
