<h2 class="title-category"><?= $tag->getTagName() ?></h2>

<div class="card-article">
    <div class="row">
        <h3>Articles</h3>
        <?php foreach($tag->getArticles() as $article) :?>
        <div class="col s12 m6">
            <div class="card brown">
                <div class="card-image">
                    <img src="<?php echo $this->basePath('/img/sample-1.jpg') ?>">
                    <span class="card-title" ><?= $article->getArtcTitle() ?></span>
                </div>
                <div class="card-content">
                    <p><?= $this->escapeHtml($article->getArtcIntrotext()) ?></p>
                </div>
                <div class="card-action">
                    <a href="<?php echo $this->url('article',
                        array('controller' => 'article', 'action' =>'view', 'id' => $article->getArtcId())).'/view/'.$article->getArtcId()?>">Lire l'article</a>
                </div>
            </div>
        </div>
        <?php endforeach ?>
    </div>
</div>