<?php

namespace DoctrineORMModule\Proxy\__CG__\Cms\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Category extends \Cms\Entity\Category implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Cms\\Entity\\Category' . "\0" . 'ctgrName', '' . "\0" . 'Cms\\Entity\\Category' . "\0" . 'articles', '' . "\0" . 'Cms\\Entity\\Category' . "\0" . 'ctgr_image_filename', '' . "\0" . 'Cms\\Entity\\Category' . "\0" . 'ctgrId');
        }

        return array('__isInitialized__', '' . "\0" . 'Cms\\Entity\\Category' . "\0" . 'ctgrName', '' . "\0" . 'Cms\\Entity\\Category' . "\0" . 'articles', '' . "\0" . 'Cms\\Entity\\Category' . "\0" . 'ctgr_image_filename', '' . "\0" . 'Cms\\Entity\\Category' . "\0" . 'ctgrId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Category $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtgrName($ctgrName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtgrName', array($ctgrName));

        return parent::setCtgrName($ctgrName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtgrName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtgrName', array());

        return parent::getCtgrName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtgrImageFileName($ctgrImageFileName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtgrImageFileName', array($ctgrImageFileName));

        return parent::setCtgrImageFileName($ctgrImageFileName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtgrImageFileName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtgrImageFileName', array());

        return parent::getCtgrImageFileName();
    }

    /**
     * {@inheritDoc}
     */
    public function getArticles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticles', array());

        return parent::getArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function addArticle(\Cms\Entity\Article $article)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticle', array($article));

        return parent::addArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticle(\Cms\Entity\Article $article)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticle', array($article));

        return parent::removeArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtgrId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCtgrId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtgrId', array());

        return parent::getCtgrId();
    }

}
