<?php
$title = 'Liste des Catégories';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>

<a href="<?php echo $this->url('cms/default', array('controller' => 'category', 'action'=>'add'));?>">Ajouter une catégorie</a>
<a href="<?php echo $this->url('cms/default', array('controller' => 'page', 'action'=>'index'));?>">Gérer les pages</a>
<table class="striped">
    <tr>
        <th>Nom</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($categories as $category):?>
        <tr>
            <td><?=$this->escapeHtml($category->getCtgrName())?>
            </td>
            <td>
                <a href="<?=$this->url('category', array('action'=>'delete', 'id' => $category->getCtgrId()))?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach?>
</table>