<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cms\Form\CategoryForm'                  => __DIR__ . '/Form/CategoryForm.php',
    'Cms\Form\PageForm'                      => __DIR__ . '/Form/PageForm.php',
    'Cms\Form\UserForm'                      => __DIR__ . '/Form/UserForm.php',
    'Cms\Module'                             => __DIR__ . '/Module.php',
    'Cms\Controller\CategoryController'      => __DIR__ . '/src/Cms/Controller/CategoryController.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Cms/Controller/IndexController.php',
    'Cms\Controller\PageController'          => __DIR__ . '/src/Cms/Controller/PageController.php',
    'Cms\Controller\UserController'          => __DIR__ . '/src/Cms/Controller/UserController.php',
    'Cms\Entity\Category'                    => __DIR__ . '/src/Cms/Entity/Category.php',
    'Cms\Entity\Page'                        => __DIR__ . '/src/Cms/Entity/Page.php',
    'Cms\Entity\User'                        => __DIR__ . '/src/Cms/Entity/User.php',
);
