<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cms-old\Form\CategoryForm'                  => __DIR__ . '/Form/CategoryForm.php',
    'Cms-old\Form\PageForm'                      => __DIR__ . '/Form/PageForm.php',
    'Cms-old\Form\UserForm'                      => __DIR__ . '/Form/UserForm.php',
    'Cms-old\Module'                             => __DIR__ . '/Module.php',
    'Cms-old\Controller\CategoryController'      => __DIR__ . '/src/Cms-old/Controller/CategoryController.php',
    'Application\Controller\IndexController' => __DIR__ . '/src/Cms-old/Controller/IndexController.php',
    'Cms-old\Controller\PageController'          => __DIR__ . '/src/Cms-old/Controller/PageController.php',
    'Cms-old\Controller\UserController'          => __DIR__ . '/src/Cms-old/Controller/UserController.php',
    'Cms-old\Entity\Category'                    => __DIR__ . '/src/Cms-old/Entity/Category.php',
    'Cms-old\Entity\Page'                        => __DIR__ . '/src/Cms-old/Entity/Page.php',
    'Cms-old\Entity\User'                        => __DIR__ . '/src/Cms-old/Entity/User.php',
);
