<h1>Retrieve your password</h1>


<div class="col s6 center-block" style="margin-top: 50px">
    <?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password')));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('usrEmail'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
    ?>

</div>