<!-- h1>I am in AuthDoctrine IndexController login action index.phtml</h1 -->
<?php echo $this->messages; ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
// echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('username'));
echo $this->formRow($form->get('password'));
echo $this->formRow($form->get('rememberme'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>


<p>
    <a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'index'));?>"><?php echo $this->translate('Register'); ?></a> |
    <a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>