<?php
$title = 'Créer un utilisateur';
$this->headTitle($title);
?>
    <nav class="nav-breadcrumb">
        <div class="nav-wrapper">
            <div class="col s12">
                <?php echo $this->escapeHtml($title); ?>
            </div>
        </div>
    </nav>
<?php

$form->prepare();

$form->setAttribute('action', $this->url('cms/default', array('controller' => 'user', 'action' => 'add')));
// Set the method attribute for the form
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

