<?php
$title = 'Liste des Users';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>

<a href="<?php echo $this->url('cms/default', array('controller' => 'user', 'action'=>'add'))?>">Créer un utilisateur</a>

<table class="striped">
    <tr>
        <th>Email</th>
        <th>Nom</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($users as $user):?>
        <tr>
            <td><a href="">
                    <?=$this->escapeHtml($user->getUsrEmail())?>
                </a>

            </td>
            <td>
                <?= $this->escapeHtml($user->getUsrName())?>
            </td>
            <td>
                <a href="<?php echo $this->url('cms/default', array('controller' => 'user', 'action'=>'edit'));?>">Modifier</a>
                <a href="<?php echo $this->url('cms/default', array('controller' => 'user', 'action'=>'delete'));?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach?>
</table>
