<?php

/*
foreach($articles AS $article) {
    echo $user->getDescription()." - ".$user->getCreated()->format('d.m.Y')."\n";
    echo "    Reported by: ".$user->getReporter()->name."\n";
    echo "    Assigned to: ".$user->getEngineer()->name."\n";
    foreach($user->getProducts() AS $product) {
        echo "    Platform: ".$product->name."\n";
    }
    echo "\n";
}
*/
$title = 'My comments';
$this->headTitle($title);
?>

<nav class="nav-breadcrumb">
    <div class="nav-wrapper">
        <div class="col s12">
            <?php echo $this->escapeHtml($title); ?>
        </div>
    </div>
</nav>

<!-- <a href="<?php echo $this->url('cms/default', array('controller' => 'comment', 'action'=>'add')); /*NOtice without true no param is send*/?>">Add new translation</a> -->
<a class="waves-effect waves-light btn" href="<?php echo $this->url('cms/default', array('controller' => 'index', 'action'=>'index'), false);?>">&lt; Back to the articles</a>
<a class="waves-effect waves-light btn" href="<?php echo $this->url('cms/default', array('controller' => 'comment', 'action'=>'add'), true);?>">Add New Comment</a>


<table class="striped">
<tr>
    <th>Title</th>
    <th>Text</th>
    <th>Author</th>
	<th>Created</th>
    <th>State</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>

</tr>

<?php foreach ($comments as $comment) : ?>
<tr>
    <td><?php echo $this->escapeHtml($comment->getComTitle());?></td>
    <td><?php echo $this->escapeHtml($comment->getComText());?></td>
    <td><?php if (is_object($comment->getAuthor())) echo $this->escapeHtml($comment->getAuthor()->getUsrName());?></td>
    <td><?php if (is_object($comment->getComCreated())) echo $this->escapeHtml($comment->getComCreated()->format('Y-m-d H:i:s'));?></td><!-- Notice: getArtcCreated() returns an object convert to string -->
    <td>
        <?php if($comment->getAuthor()->getUsrId() == $user = $this->identity()->getUsrId() && $comment->getComActive() ) :?>
            <span style="color: #fff;" class="badge light-green darken-4">Active</span>
            <a class="waves-effect waves-light btn" href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment> NOT ONLY cms
                array('controller' => 'comment', 'action'=>'desactive', 'id' => $comment->getComId()));?>">Desactive</a>
        <?php else: ?>
            <span  style="color: #fff;" class="badge deep-orange accent-4">Desactive</span>
            <a class="waves-effect waves-light btn" href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment> NOT ONLY cms
                array('controller' => 'comment', 'action'=>'active', 'id' => $comment->getComId()));?>">Active</a>
        <?php  endif ?>

    </td>
    <td>
        <a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use grace-drops/<segment> NOT ONLY grace-drops
            array('controller' => 'comment', 'action'=>'edit', 'id2' => $comment->getComId()), true);?>">Edit</a>
        <a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use grace-drops/<segment>
            array('controller' => 'comment', 'action'=>'delete', 'id2' => $comment->getComId()), true);?>" onclick="return confirm('Do you rely want to delete the record?')">Delete</a>
    </td>

</tr>
<?php endforeach; ?>
</table>