<?php
/*
foreach($articles AS $article) {
    echo $user->getDescription()." - ".$user->getCreated()->format('d.m.Y')."\n";
    echo "    Reported by: ".$user->getReporter()->name."\n";
    echo "    Assigned to: ".$user->getEngineer()->name."\n";
    foreach($user->getProducts() AS $product) {
        echo "    Platform: ".$product->name."\n";
    }
    echo "\n";
}
*/
$title = 'Liste des articles';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="waves-effect waves-light btn" href="<?php echo $this->url('cms/default', array('controller' => 'index', 'action'=>'add'));?>">Add article</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Intro Text</th>
    <th>Author</th>
    <th>Language</th>
	<th>Parent</th>
	<th>Created</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($articles as $article) : ?>
<tr>
    <td><?php echo $this->escapeHtml($article->getArtcTitle());?></td>
    <td><?php echo $this->escapeHtml($article->getArtcIntrotext());?></td>
    <td><?php if (is_object($article->getAuthor())) echo $this->escapeHtml($article->getAuthor()->getUsrName());?></td>
    <td><?php if (is_object($article->getLanguage())) echo $this->escapeHtml($article->getLanguage()->getLngName());?></td>
    <td><?php if (is_object($article->getParent())) echo $this->escapeHtml($article->getParent()->getArtcTitle());?></td>
    <td><?php echo $this->escapeHtml($article->getArtcCreated()->format('Y-m-d H:i:s'));?></td><!-- Notice: getArtcCreated() returns an object convert to string -->
    <td>
        <a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment> NOT ONLY cms
            array('controller' => 'translation', 'action'=>'index', 'id' => $article->getArtcId()));?>">Translations</a>
        <a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment> NOT ONLY cms
            array('controller' => 'comment', 'action'=>'index', 'id' => $article->getArtcId()));?>">Comments</a>
        <a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment> NOT ONLY cms
            array('controller' => 'index', 'action'=>'view', 'id' => $article->getArtcId()));?>">View</a>
		<a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment> NOT ONLY cms
            array('controller' => 'index', 'action'=>'edit', 'id' => $article->getArtcId()));?>">Edit</a>
        <a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment>
            array('controller' => 'index', 'action'=>'delete', 'id' => $article->getArtcId()));?>" onclick="return confirm('Do you rely want to delete the record?')">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>