<?php
echo '<h1>Edit Article</h1>';

$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('cms/default', array('controller' => 'translation', 'action' => 'edit', 'id2' => $this->id), true)); //'contact/process'));
// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();