<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('CMS '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>

<nav>
    <div class="nav-wrapper">
        <a class="brand-logo right" href="<?php echo $this->url('home') ?>">CMS</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
            <?php if (!$user = $this->identity()) { ?>
            <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                <li><a href="<?php echo $this->url('auth') ?>"><?php echo $this->translate('login') ?></a></li>
            <?php }else { ?>


            <li class="">
                <?php if ($user = $this->identity()) {
                    echo 'Bonjour,  ' . $this->escapeHtml($user->getUsrName());
                    ?>
                    | <a href="<?php echo $this->url('auth/default', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>
                    <?php
                } else {
                    echo 'Not logged in';
                }?>
            </li>
            <li><a href="<?php echo $this->url('auth') ?>"><?php echo $this->translate('Users') ?></a></li>
            <li><a href="<?php echo $this->url('category') ?>"><?php echo $this->translate('Categories') ?></a></li>
            <li><a href="<?php echo $this->url('page') ?>"><?php echo $this->translate('Pages') ?></a></li>

           <li><a href="<?php echo $this->url('csn-cms') ?>"><?php echo $this->translate('Articles') ?></a></li>
            <?php } ?>
        </ul>


    </div>
</nav>

<div class="container">

    <div class="row">



        <div class="col s12"> <!-- Note that "m8 l9" was added -->
                <?php echo $this->content; ?>

            </div>

        </div>

    </div>

    <hr>
    <footer>

    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
