<?php
echo '<h1>Add Page</h1>';
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('cms/default', array('controller' => 'page', 'action' => 'add'), true));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
