

<?php
$title = 'Créer une page';
$this->headTitle($title);
?>

<nav class="nav-breadcrumb">
    <div class="nav-wrapper">
        <div class="col s12">
            <?php echo $this->escapeHtml($title); ?>
        </div>
    </div>
</nav>

<?php
$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('cms/default', array('controller' => 'page', 'action' => 'add','id' => 'theform'), true));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>
<button class="btn waves-effect waves-light" id="addWidgetButton">Add block page</button>
<section class="demo">
    <div class="gridster">
        <ul>
            <li data-row="1" data-col="1" data-sizex="1" data-sizey="1" data-id="1">
                <h1>Bloc 1</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="1" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal-1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="2" data-col="1" data-sizex="1" data-sizey="1" data-id="2">
                <h1>Bloc 2</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="2" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal-2" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="3" data-col="1" data-sizex="1" data-sizey="1" data-id="3">
                <h1>Bloc 3<h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="3" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal-3" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="1" data-col="2" data-sizex="4" data-sizey="1" data-id="4">
                <h1>Header</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="4" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="2" data-col="2" data-sizex="4" data-sizey="2" data-id="5">
                <h1>Content</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="5" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="1" data-col="4" data-sizex="1" data-sizey="1" data-id="6">
                <h1>Bloc 6</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="6" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="2" data-col="4" data-sizex="1" data-sizey="1" data-id="7">
                <h1>Bloc 7</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="7" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="3" data-col="4" data-sizex="1" data-sizey="1" data-id="8">
                <h1>Bloc 8</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="8" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="5" data-col="1" data-sizex="6" data-sizey="1" data-id="9">
                <h1>Bloc 9</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="9" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="4" data-col="1" data-sizex="1" data-sizey="1" data-id="10">
                <h1>Bloc 10</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="10" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="4" data-col="2" data-sizex="4" data-sizey="1" data-id="11">
                <h1>Bloc 11</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="11" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
            <li data-row="4" data-col="3" data-sizex="1" data-sizey="1" data-id="12">
                <h1>Bloc 12</h1>
                <img style="height:20px;top:5px;left:5px;position:absolute" src="<?php echo $this->basePath('img/close.png') ?>" data-close="12" class="close"/>
                <i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal1" class="material-icons modal-trigger" data-settings="1">settings</i>
            </li>
        </ul>
    </div>
</section>

<!-- Modal Structure -->
<div id="modal-1" class="modal">
    <div class="modal-content">
        <h4>Modal Header 1</h4>
        <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
</div>

<!-- Modal Structure -->
<div id="modal-2" class="modal">
    <div class="modal-content">
        <h4>Modal Header 2</h4>
        <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
</div>

<!-- Modal Structure -->
<div id="modal-3" class="modal">
    <div class="modal-content">
        <h4>Modal Header 3</h4>
        <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
<script src="<?php echo $this->basePath('lib/gridster/dist/jquery.gridster.min.js') ?>"></script>

<script type="text/javascript">
    var gridster;
    var cpt =12;
    var diff=0;
    var dataOldId= [];

    $(function() {
        gridster = $(".gridster > ul").gridster({
            widget_margins: [10, 10],
            widget_base_dimensions: [140, 140],
            min_cols: 6,
            max_cols:12,

            resize: {
                enabled: true,
                start: function (e, ui, $widget) {

                },
                stop: function (e, ui, $widget) {
                    var newHeight = this.resize_coords.data.height;
                    var newWidth = this.resize_coords.data.width;

                }
            },
        }).data('gridster');

        $(".gs-w").hover(function (){
            var id = $(this).attr("data-id");
            //show close button on hover
            $("ul").find("[data-close='" + id + "']").show();
            //show modifie button on hover
            $("."+id).show();
        });
       
        closeWidget();

        function closeWidget() {
            $(".close").click(function(){
                var id=$(this).attr("data-close");
                //$("ul").find("[data-id='" + id + "']").remove();
                gridster.remove_widget($("ul").find("[data-id='" + id + "']"));
                cpt--;
                diff++;
                dataOldId[diff] = id;
            });
        }

        $(document).on( "click", "#addWidgetButton", function(e) {
            console.log(dataOldId);
            if(cpt!=12) {
                cpt++;
                e.preventDefault();
                gridster.add_widget.apply(gridster, ['<li data-id="'+dataOldId[diff]+'"><h1>New bloc</h1>' +
                '<img src="<?php echo $this->basePath('img/close.png') ?>" style="height:20px;top:5px;left:5px;position:absolute" data-close="'+dataOldId[diff]+'" class="close"/>' +
                '<i style="height:20px;top:5px;right:5px;position:absolute" data-target="modal-'+dataOldId[diff]+'" class="material-icons modal-trigger" data-settings="1">settings</i></li>', 1, 1]);
                diff--;
                closeWidget();
            }
        });

        $('.btn-submit-form-page').click(function() {
            cpt++;
            diff--;
            var gridster = $(".gridster ul").gridster().data('gridster');
            gridData = gridster.serialize();
            $('#structureform').val(JSON.stringify(gridData));
            $("#theform").submit();
        });

    });
</script>
