<?php
$title = 'Supprimer la page';
$this->headTitle($title);
$url = $this->url('page', array('action' => 'delete', 'id'=>$this->id))
?>
<h1><?=$this->escapeHtml($title)?></h1>
Etes-vous sûr de vouloir supprimer la categorie "<?=$this->escapeHtml($page->title)?>" ?
<form action="<?=$url?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?=$page->id?>" />
        <input type="submit" name="del" value="Oui" />
        <input type="submit" name="del" value="Non" />
    </div>
</form>