
<?php
$title = 'Modifier la Page';
$this->headTitle($title);
$form = $this->form;
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('cms/default', array('controller' => 'page', 'action' => 'edit', 'id'=>$this->id), true));

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

