<?php
$title = 'Liste des Pages';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<a href="<?php echo $this->url('cms/default', array('controller' => 'page', 'action'=>'add'), false);?>">Ajouter une page </a> |
<a href="<?php echo $this->url('cms/default', array('controller' => 'category', 'action'=>'index'), false);?>">Gérer les catégories</a>
<table class="striped">
    <tr>
        <th>Titre</th>
        <th>Contenu</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($pages as $page):?>
        <tr>
            <td><a href="<?=$this->url('page', array('action'=>'view', 'id' => $page->id))?>">
                    <?=$this->escapeHtml($page->title)?>
                </a>
                <?php if($page->category != null):?>
                    (<?=$this->escapeHtml($page->category->name)?>)
                <?php endif?>
            </td>
            <td>
                <?=$this->escapeHtml($page->content)?>
            </td>
            <td>
                <a href="<?=$this->url('page', array('action'=>'edit', 'id' => $page->id))?>">Modifier</a>
                <a href="<?=$this->url('page', array('action'=>'delete', 'id' => $page->id))?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach?>
</table>
