<div class="gridster">
    <ul>
    </ul>
</div>


<script src="<?php echo $this->basePath('lib/gridster/dist/jquery.gridster.min.js') ?>"></script>

<script type="text/javascript">
    var gridster;

        // sort serialization
        serialization = <?= $page->structure ?>;

    console.log(serialization)

        $(function(){

            gridster = $(".gridster ul").gridster({
                widget_base_dimensions: [140, 140],
                widget_margins: [5, 5],
                min_cols: 6,
                max_cols:12,
                draggable: {ignore_dragging: true},
            }).data('gridster');


            placementObject();

            function placementObject() {
                gridster.remove_all_widgets();
                $.each(serialization, function() {
                    gridster.add_widget('<li />', this.size_x, this.size_y, this.col, this.row);
                });

            }

        });



</script>

