<?= $page->title ?> <br>

<?= $page->content ?> <br>

<?= $page->id ?>

<?= $page->structure ?>

<div class="controls">
    <button class="js-seralize">Build from serialize</button>
</div>

<div class="gridster">
    <ul>
    </ul>
</div>


<script src="<?php echo $this->basePath('lib/gridster/dist/jquery.gridster.min.js') ?>"></script>

<script type="text/javascript">
    var gridster;

        // sort serialization
        serialization = <?= $page->structure ?>;

    console.log(serialization)

        $(function(){

            gridster = $(".gridster ul").gridster({
                widget_base_dimensions: [100, 55],
                widget_margins: [5, 5]
            }).data('gridster');


            $('.js-seralize').on('click', function() {
                gridster.remove_all_widgets();
                $.each(serialization, function() {
                    gridster.add_widget('<li />', this.size_x, this.size_y, this.col, this.row);
                });
            });

        });


    
</script>

