<div class="gridster">
    <ul>
    </ul>
</div>

<script src="<?php echo $this->basePath('lib/gridster/dist/jquery.gridster.js') ?>"></script>

<script type="text/javascript">
    var gridster;
    // sort serialization
    serialization = <?= $page->structure ?>;
    $array = <?= $page->block_element ?>;

    $(function(){

        gridster = $(".gridster ul").gridster({
            widget_base_dimensions: [140, 200],
            widget_margins: [5, 5],
            min_cols: 6,
            max_cols:12,
            draggable: {ignore_dragging: true}
        }).data('gridster');

        placementObject();

        function placementObject() {
            gridster.remove_all_widgets();
            $.each(serialization, function() {
                $html ='<li />';
                $w = gridster.add_widget($html, this.size_x, this.size_y, this.col, this.row);
                $w.attr('data-id', this.id)

            });
            $.each($array, function() {
                $wi = $(".gridster > ul li").filter('[data-id="'+ this.element_id+'"]').attr('data-id', this.element_id);
                $(".gridster > ul li").filter('[data-id="'+ this.element_id+'"]').attr('data-id', this.element_id).html(this.element_type)
                applyStyleToElement(this.element_type, $wi)
            })
        }

        function applyStyleToElement($type, $wi) {
            switch($type) {
                case 'menu':
                    $wi.append("<b>Appended html</b>");
                    break;
                case 'article':
                    break;

            }
        }
    });
</script>

