<nav class="nav-breadcrumb">
    <div class="nav-wrapper">
        <div class="col s12">
            <?php foreach($list as $item) :?>
                <span style="font-size:<?php echo $item->getParam('weightValue'); ?>%">
                    <a href="<?php echo $this->url('tag',
                                                   array('controller' => 'tag', 'action' =>'view', 'id' => $item->getParam('id'))).'/view/'.$item->getParam('id') ;?>">
                        <?php echo $this->escapeHtml($item->getTitle());?>
                    </a>
                </span>
            <?php endforeach ?>
        </div>
    </div>
</nav>
<div class="row">
    <?php foreach($categories as $category) :?>
        <div class="col s12 m4">
            <div class="card brown">
                <div class="card-image">
                    <img src="<?php echo $this->basePath('/uploads/'.$category->getCtgrImageFilename()) ?>"  style="height: 220px">
                    <span class="card-title" style="color: #3949ab;font-weight: 700" ><?php echo $this->escapeHtml($category->getCtgrName());?></span>
                </div>
                <div class="card-action" style="text-align: center;">
                    <a href="<?php echo $this->url('category',
                            array('controller' => 'category', 'action' =>'view', 'id' => $category->getCtgrId())).'/view/'.$category->getCtgrId() ;?>">View</a>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>