<?php
$title = 'Créer un theme';
$this->headTitle($title);
?>

    <nav class="nav-breadcrumb">
        <div class="nav-wrapper">
            <div class="col s12">
                <?php echo $this->escapeHtml($title); ?>
            </div>
        </div>
    </nav>


<?php


$form = $this->form;
$form->prepare();

$form->setAttribute('action', $this->url('cms/default', array('controller' => 'theme', 'action' => 'add'), true)); //'contact/process'));

$form->setAttribute('method', 'post');

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
