<?php
$title = 'Liste des Themes';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<a class="waves-effect waves-light btn" href="<?php echo $this->url('cms/default', array('controller' => 'theme', 'action'=>'add'), false);?>">Ajouter un theme </a>
<table class="striped">
    <tr>
        <th>Name</th>
        <th>Active</th>
    </tr>
    <?php foreach($themes as $theme):?>
        <tr>
            <td><?php echo $theme->getThemeName()?></td>

            <td>
                <div class="switch">
                    <label>
                        Off
                        <input type="checkbox">
                        <span class="lever"></span>
                        On
                    </label>
                </div>
            </td>
        </tr>
    <?php endforeach?>
</table>
