<?php
$title = 'Liste des Themes';
$this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<table class="striped">
    <tr>
        <th>Name</th>
        <th>Active</th>
    </tr>
    <?php foreach($themes as $theme):?>
        <tr>
            <td><?php echo $theme->getThemeName()?></td>
            <td>

                <a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment> NOT ONLY cms
                    array('controller' => 'theme', 'action'=>'active', 'id' => $theme->getThemeId()));?>">Active</a>

                <a href="<?php echo $this->url('cms/default', // SUPER IMPORTANT use cms/<segment> NOT ONLY cms
                    array('controller' => 'theme', 'action'=>'desactive', 'id' => $theme->getThemeId()));?>">Desactive</a>

            </td>
        </tr>
    <?php endforeach ?>
</table>


